# Generated by Django 3.2.6 on 2021-08-19 11:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0003_auto_20210819_1644'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentGrades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grades', models.CharField(max_length=4, validators=[django.core.validators.MaxLengthValidator(1)], verbose_name='grades')),
            ],
        ),
    ]
