# Generated by Django 3.2.6 on 2021-08-19 12:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0004_studentgrades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentgrades',
            name='grades',
            field=models.CharField(max_length=1, validators=[django.core.validators.MaxLengthValidator(1)], verbose_name='grades'),
        ),
    ]
