# Generated by Django 3.2.6 on 2021-08-19 14:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0006_studentmarks_studentgrade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmarks',
            name='marks',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
    ]
